### ISSUE TITLE
http://vmbox.metacpan.org/ is 403 fobidden

### ISSUE THREAD

**Issue by kwakwaversal** [metacpan/metacpan-developer#42]
The Vagrant base image http://vmbox.metacpan.org/mcwheezy_vm_debian_006_32.box doesn't work as the entire http://vmbox.metacpan.org/ is returning 403 forbidden.

Would it be possible to host the box(es) on https://app.vagrantup.com/ in the future?

**Comment by ranguard** [comment]
I've fixed this with a quick fix that should get you doing... good idea about hosting there in the future - @oalders is working on a new .box so we should switch to that when we have it ready
