### ISSUE TITLE
Last CPAN clone command fails

### ISSUE THREAD

**Issue by talexb** [metacpan/metacpan-developer#6]
The final command for the cloning of CPAN (in the Set up a CPAN mirror section) fails:

```
metacpan@debian:~$ wget -P /home/metacpan/CPAN -nv -e robots=off -nH -r -l 1 $CPAN_MIRROR/indices/
http://cpan.perlnow.com//indices/:
2013-07-30 14:46:22 ERROR 403: Forbidden.
metacpan@debian:~$ echo $CPAN_MIRROR
http://cpan.perlnow.com/
metacpan@debian:~$
```

As directed, the '--cut-dir=1' argument was removed from the command line because the CPAN mirror (shown above) did not include a directory path.

**Comment by oalders** [comment]
This appears to be fixed.  Thanks @talexb for reporting!
